### PR TITLE
Add maintainers file.

### PR DESCRIPTION
**Pull request by calavera**
/cc @thaJeztah

Signed-off-by: David Calavera <david.calavera@gmail.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM, (same list as for "engine-api"?) thanks! 

ping @vdemeester we were discussing this; did we miss any here?

**Comment by vdemeester** [comment]
@thaJeztah nop, I don't think we missed anything :angel: Having the same list as `engine-api` is a good start I feel :+1: 
LGTM 🐰

**Comment by thaJeztah** [comment]
ping @icecrime @crosbymichael as well, for setting up permissions once this is accepted

**Comment by calavera** [comment]
We got this repo in the engine-maintainers team. :tada:

**Pull request merged**
