### PR TITLE
Enabled ppc64le as an architecture

### PR DESCRIPTION
**Pull request by vrushaliinamdar**
Enabled ppc64le under "arch" instead of specifying under "os"
arch:
    - ppc64le

### CODE REVIEW

**Comment by vrushaliinamdar** [comment]
Hi Team,

Could you please comment on this request?

**Comment by clnperez** [comment]
Hi @vrushaliinamdar -- this is a dup of https://github.com/docker/docker-credential-helpers/issues/144. Have you considered submitting a PR for this update yourself? We know that this project does build easily on ppc64le.

**Comment by thaJeztah** [comment]
I don't think this change currently does what it was intended to do, because now it _only_ runs on ppc64le, so looks like more changes are needed;

Screenshot 2021-01-20 at 10 59 17

**Comment by thaJeztah** [comment]
We enabled cross-builds for s390x and ppc64le in https://github.com/docker/docker-credential-helpers/pull/227

**Pull request closed without merging**
