### PR TITLE
A new entry point for calling the cred helpers that allow passing environment variables

### PR DESCRIPTION
**Pull request by shhsu**
This change introduce a new entry point for credential helpers. The caller can now pass environment variable so that the credential helper can be aware of them.

The motivation of this feature is that Azure Container Registry is developing a credential helper that wants to know which docker file is currently active. Note that when `docker` command was called with `--config` flag, there is currently no way for docker to pass that information to the credential helper.

This feature will allow changes to be made in docker cli so it could, for example set the `DOCKER_CONFIG` environmental variable before calling the credential helper.

### CODE REVIEW

**Comment by shhsu** [comment]
@sajayantony @davidobando

**Comment by n4ss** [comment]
I like this, too bad we weren't doing this before :)

**Comment by shhsu** [comment]
Updated as requested

**Comment by DavidObando** [comment]
Ping.

**Comment by n4ss** [comment]
@vdemeester @thaJeztah WDYT?

**Comment by n4ss** [comment]
LGTM

**Pull request merged**
