### PR TITLE
README update to add homebrew installation help

### PR DESCRIPTION
**Pull request by danshumaker**
This tripped me up for a few minutes, so I thought it would be helpful to add to the README.

### CODE REVIEW

**Comment by n4ss** [comment]
LGTM

/cc @vdemeester

**Comment by promiseofcake** [comment]
This has actually been changed to `docker-credential-helper`. Via: https://github.com/Homebrew/homebrew-core/blob/master/Formula/docker-credential-helper.rb

**Comment by guillaumerose** [comment]
@danshumaker Can you update the PR with the correct formula name so that I can merge ?

Thanks and sorry for the delay

**Comment by danshumaker** [comment]
@guilamarose not sure i know what you mean. Seems like from promiseofcake that my change is not necessary. I said the formula was docker-credential-osxhelper but it looks like docker-credential-helper is now the right one. Haven’t tested it in a couple years.

**Comment by Tyson1986** [comment]
For me 
`brew install docker-credential-helper`
works, and 
`brew install docker-credential-osxhelper`
does not work.

**Pull request closed without merging**
