### PR TITLE
Adding power support

### PR DESCRIPTION
**Pull request by ghatwala**
- Adding ppc64le build to travis.yml
- Adding xvfb service start for ppc64le

### CODE REVIEW

**Comment by ghatwala** [comment]
@GordonTheTurtle - any pointers to resolve this failure -  https://travis-ci.org/docker/docker-credential-helpers/jobs/534754946#L400 as regards to "username" ?

**Comment by clnperez** [comment]
@GordonTheTurtle is a bot. Can you try doing a force-push to re-run those tests? That failure looks like it might just be flaky.

**Comment by ghatwala** [comment]
@clnperez - sure , done a force-push ..will check for that TC .

**Comment by clnperez** [comment]
Strange. If I run this test locally (just `make test`) that passes.

**Comment by ghatwala** [comment]
Messed up this PR , found the issue why it wasn't on power .closing this PR in favor of this PR - https://github.com/docker/docker-credential-helpers/pull/160

**Pull request closed without merging**
