### PR TITLE
Implementing listing functionality across OSX, Linux and Windows

### PR DESCRIPTION
**Pull request by avaid96**

### CODE REVIEW

**Comment by calavera** [comment]
What about Windows? We should not add functionality that's not compatible with all major providers.

**Comment by calavera** [comment]
Is this returning all the keys in the secrets store regardless whether you need them or not? Doesn't that open the door to leaking credentials? I'd rather not expose all your credentials from your computer.

**Comment by avaid96** [comment]
How would you decide whether you need them or not?

**Comment by avaid96** [comment]
pending: Implementation at a client level. Currently functional on the credentials level

**Comment by avaid96** [comment]
pending: Windows functionality. 
"osxkeychain_darwin_test.go:44: An invalid record was encountered" failure in travis, this error doesn't persist on my local system, tried on a friend's mac as well and he doesn't run into the issue. Travis uses OsX 10.9 and the error seems to be associated with SecItemCopyMatching which seems to be supported 10.6+

**Comment by avaid96** [comment]
Update: Windows functionality is complete on the WinCred side. I have opened a PR for danieljoos to merge. Once that is complete, Windows should be working as well
Pending: Fixing what is causing the OSX test to fail on Travis. Would appreciate any pointers you may have in terms of weirdness of OSX on Travis v/s local system

**Comment by avaid96** [comment]
Update: Windows functionality is complete on the WinCred side. I have opened a PR for danieljoos to merge. Once that is complete, Windows should be working as well
Pending: Complete Windows once the merge is complete

**Comment by avaid96** [comment]
Complete functionality for listing in Windows, OSX and Linux. Pending your review @calavera

**Comment by calavera** [comment]
Awesome! LGTM.

I'm going to merge this but it will take me a few days to ship a new release. I have to re-add the appveyor bot and I lost privileges to see the settings in this repository. :pensive:

**Comment by avaid96** [comment]
Thanks a ton for the quick merge. Sure, no issues!

**Pull request merged**
