### PR TITLE
Dockerfile: update xx to v1.4.0

### PR DESCRIPTION
**Pull request by thaJeztah**
full diff: https://github.com/tonistiigi/xx/compare/v1.2.1...v1.4.0

### CODE REVIEW

**Comment by thaJeztah** [comment]
Unfortunately; still failing with newer go versions; we'll have to look what's causing it; /cc @crazy-max 


```
91.42 go build -trimpath -ldflags="-s -w -X github.com/docker/docker-credential-helpers/credentials.Version=v0.8.0-10-g59ccf8f -X github.com/docker/docker-credential-helpers/credentials.Revision=59ccf8f9aafca3c2f75d9cafde97f514aa48d2f2 -X github.com/docker/docker-credential-helpers/credentials.Package=github.com/docker/docker-credential-helpers -X github.com/docker/docker-credential-helpers/credentials.Name=docker-credential-osxkeychain" -o "/out/docker-credential-osxkeychain" ./osxkeychain/cmd/
121.4 # github.com/docker/docker-credential-helpers/osxkeychain/cmd
121.4 /usr/local/go/pkg/tool/linux_amd64/link: running arm64-apple-macos10.11-clang failed: exit status 255
121.4 /usr/bin/arm64-apple-macos10.11-ld: 9: sigtool-gensig: not found
121.4 clang: error: unable to execute command: No such file or directory
121.4 clang: error: linker command failed due to signal (use -v to see invocation)
```

**Comment by thaJeztah** [comment]
Maybe we need to update `OSXCROSS_VERSION` or something

**Comment by thaJeztah** [comment]
Pushed a temporary commit to use `xx:master`; @crazy-max thinks this may be related to 

- https://github.com/tonistiigi/xx/pull/140#discussion_r1444242053

**Comment by crazy-max** [comment]
> Pushed a temporary commit to use `xx:master`; @crazy-max thinks this may be related to
> 
>     * [ld: update ld64 and dependencies  tonistiigi/xx#140 (comment)](https://github.com/tonistiigi/xx/pull/140#discussion_r1444242053)

Still sad :(

```
115.0 # github.com/docker/docker-credential-helpers/osxkeychain/cmd
115.0 /usr/local/go/pkg/tool/linux_amd64/link: running arm64-apple-macos10.11-clang failed: exit status 255
115.0 /usr/bin/arm64-apple-macos10.11-ld: 9: sigtool-gensig: not found
```

We need new prebuild-ld, I'm looking into it and keep you posted.

**Comment by thaJeztah** [comment]
`arm64-apple-macos10.11-clang` looks like that's  for a different version than `OSXCROSS_VERSION=11.3-r7-debian` is that related in any form?

**Comment by crazy-max** [comment]
@thaJeztah CAn you try with latest `v1.4.0`? https://github.com/tonistiigi/xx/releases/tag/v1.4.0

**Comment by thaJeztah** [comment]
updated 🤞

**Review by crazy-max — APPROVED** [review]

**Pull request merged**
