### PR TITLE
secretservice: add D-Bus secret service

### LINKED ISSUE #5: Add support for Gnome keyring
Because 20xx is the year of Linux on the desktop.

### PR DESCRIPTION
**Pull request by runcom**
Fixes #5 

:angel: cause we <3 linux

this implements a credential store with `libsecret-1` and I called it *secretservice* (there will be other creds store for linux in the future though :smile_cat: )

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by runcom** [comment]
@calavera we should fix CI

**Comment by runcom** [comment]
I swear I did my best to let tests run for secretservice but it actually requires gnome-keyring and travis doesn't have it yet. At least I was able to split out the tests on travis to do both osx and linux + I fixed golint.

**Comment by calavera** [comment]
Thanks @runcom! LGTM

**Comment by calavera** [comment]
I'm going to merge. I'll make the changes to the deploy script soon.

**Pull request merged**
